from fastapi import APIRouter
import importlib

router = APIRouter(
    prefix="/optimization",
    tags=["Optimization"]
)


@router.post("/")
def run_optimization():

    try:
        # Import optimizer module
        optimizer = importlib.import_module(
            "logic.block_optimizer"
        )

        # Reload so optimization runs every time
        optimizer = importlib.reload(optimizer)

        # Get results generated by block_optimizer.py
        optimized_blocks = getattr(
            optimizer,
            "optimized_blocks",
            []
        )

        requests = getattr(
            optimizer,
            "requests",
            []
        )

        return {
            "status": "success",
            "message": "Optimization completed successfully",
            "requests_processed": len(requests),
            "blocks_generated": len(optimized_blocks),
            "blocks": [
                {
                    "block_id": block["block_id"],
                    "corridor": block["corridor"],
                    "date": str(block["date"]),
                    "start": str(block["start"]),
                    "end": str(block["end"]),
                    "duration": block["duration"],
                    "utilization": block["utilization"],
                    "train_impact": block["train_impact"],
                    "number_of_tasks": len(block["tasks"]),
                    "train_conflicts": len(
                        block["train_conflicts"]
                    )
                }
                for block in optimized_blocks
            ]
        }

    except Exception as e:

        return {
            "status": "error",
            "message": str(e)
        }